### ISSUE TITLE
The files required by running train.py are missing

### ISSUE THREAD

**Issue by anxiangbiye1231** [EricZhangSCUT/SPIN-CGNN#2]
Dear authors,
Nice study. I want to train the model on whole CATH 4.2 to reproduce the performance recorded in the paper. However, the files required by running train.py, such as train-CGraph10.pkl, are missing. Could you please upload the related files again?

**Comment by EricZhangSCUT** [comment]
The training data for CATH4.2 can be generated using a script from our previous work, available here: [neurips19-graph-protein-design](https://github.com/jingraham/neurips19-graph-protein-design/blob/master/data/build_chain_dataset.py). Additionally, we have provided the append_cgraph function in data_preprocess.py to construct a contact-based graph for the preprocessed entries from CATH4.2.
