### ISSUE TITLE
About CATH4.2-StructNR193

### ISSUE THREAD

**Issue by anxiangbiye1231** [EricZhangSCUT/SPIN-CGNN#4]
Dear authors,
I don't find the dataset named CATH4.2-StructNR193 in this repository. Could you please share it again？ I would like to evaluate our own model on this test set. Thank you so much！

**Comment by EricZhangSCUT** [comment]
The name list of CATH4.2-StructNR193 test set has now been uploaded. Thank you for bringing this to our attention.
